package autoswitch

import (
	"strconv"
	"strings"
)

// LaunchdLabel is the launchd job label and the plist file's base name.
const LaunchdLabel = "com.drogers0.aistat.autoswitch"

// PlistXML renders the launchd agent definition. Thresholds are deliberately
// NOT baked in — the invoked `switch --if-needed` resolves them from the env
// file on every run, so changing them never requires a plist reload.
func PlistXML(binaryPath string, intervalSeconds int, logPath string) string {
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>` + LaunchdLabel + `</string>
	<key>ProgramArguments</key>
	<array>
		<string>` + xmlEscape(binaryPath) + `</string>
		<string>switch</string>
		<string>--if-needed</string>
		<string>--notify</string>
	</array>
	<key>StartInterval</key>
	<integer>` + strconv.Itoa(intervalSeconds) + `</integer>
	<key>StandardOutPath</key>
	<string>` + xmlEscape(logPath) + `</string>
	<key>StandardErrorPath</key>
	<string>` + xmlEscape(logPath) + `</string>
</dict>
</plist>
`
}

func xmlEscape(s string) string {
	return strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;").Replace(s)
}

// ParseInterval extracts StartInterval from a plist previously generated by
// PlistXML (used by `autoswitch status`). ok=false when absent or malformed.
func ParseInterval(plistXML string) (int, bool) {
	const marker = "<key>StartInterval</key>"
	i := strings.Index(plistXML, marker)
	if i < 0 {
		return 0, false
	}
	rest := plistXML[i+len(marker):]
	open := strings.Index(rest, "<integer>")
	end := strings.Index(rest, "</integer>")
	if open < 0 || end < 0 || end < open {
		return 0, false
	}
	n, err := strconv.Atoi(strings.TrimSpace(rest[open+len("<integer>") : end]))
	if err != nil {
		return 0, false
	}
	return n, true
}
